config/routes.rb
Rails.application.routes.draw do
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
   sessions: "admin/sessions"
  }
  
  
  namespace :admin do
    devise_scope :admin do
      get '/sign_in' => 'sessions#new'
      post '/sign_in' => 'sessions#create'
      delete '/sign_out' => 'sessions#destroy'
    end  
    get '' => 'homes#top'
    resources :items, except: [:destroy]
    resources :genres, only: [:create, :index, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update]
    resources :order_details, only: [:update]
  end
  
  
  
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers, skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
  }
  root to: 'public/homes#top'
  get 'about' => 'public/homes#about', as: '/about'
  
  scope module: :public do
    
    get '/customers/my_page' => 'customers#show'
    get '/edit/customers' => 'customers#edit'
    patch 'update/customers' => 'customers#update'
    resources :customers, only: [:edit, :update, :show] do
      collection do
  	     get 'unsubscribe'
  	     patch 'withdraw'
  	  end
  	end  
    #get '/customers/unsubscribe' => 'customers#unsubscribe'
    #patch '/customers/withdraw' => 'customers#withdraw' 
    
    
    
    resources :items, only: [:index, :show]
    
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    resources :cart_items, only: [:create, :destroy, :update]
    #delete '/cart_items/:id' => 'cart_items#destroy'
    get '/cart_items' => 'cart_items#cart'
   
    post '/orders/confirm' => 'orders#confirm'
    get '/orders/complete' => 'orders#order_complete'
    resources :orders, only: [:new, :create, :show, :index]
   
    
    resources :addresses, only: [:index, :create, :destroy, :edit, :update]
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_header.html.erb
<header class="navbar navbar-default">
  <div class="container-fluid">

      <!--ロゴ-->
      <nav class="nav navbar-header navbar-left">
        <div class="logo">
          <%= link_to root_path do %>
            <%= image_tag 'logo.jpg', class: "logo_image", fallback: "ロゴ画像" %>
          <% end %>
        </div>
      </nav>

      <!--メニューボタン-->
      <nav>
        <ul class="navbar-nav navbar-expand-lg">
          <% if admin_signed_in? %>
            <li class="button-admin"><%= link_to "商品一覧", admin_items_path, class:"btn btn-default btn-lg admin-button" %> </li>
            <li class="button-admin"><%= link_to "会員一覧", admin_customers_path, class:"btn btn-default btn-lg admin-button" %></li>
            <li class="button-admin"><%= link_to "注文履歴一覧", admin_orders_path, class:"btn btn-default btn-lg admin-button" %></li>
            <li class="button-admin"><%= link_to "ジャンル一覧", admin_genres_path, class:"btn btn-default btn-lg admin-button" %></li>
            <li class="button-admin"><%= link_to "ログアウト", admin_sign_out_path, method: :delete, class:"btn btn-default btn-lg admin-button" %></li>
          <% else %>
            <li class="button-admin"><%= link_to " About ", about_path, class:"btn btn-default btn-lg" %></li>
            <li class="button-admin"><%= link_to " 商品一覧 ", items_path, class:"btn btn-default btn-lg" %></li>
            <li class="button-admin"><%= link_to " 新規登録 ", new_customer_registration_path, class:"btn btn-default btn-lg" %></li>
            <li class="button-admin"><%= link_to " ログイン ", new_customer_session_path, class:"btn btn-default btn-lg" %></li>
          <% end %>
        </ul>
      </nav>
      <br></br><br></br></br>
    <% if admin_signed_in? %>
    <div class="search-form">
      <%= form_tag(items_path,:method => 'get') do %>
        <%= text_field_tag :name %>
        <%= submit_tag '検索' %>
      <% end %>
    </div>
    <% end %>
  </div>
</header>

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
 <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>©2022 nagano-cake</p>
          </div>
        </div>
        </div>
    </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="container-fluid">

      <!--ロゴ-->
      <nav class="nav navbar-header navbar-left">
        <div class="logo">
          <%= link_to root_path do %>
            <%= image_tag 'logo.jpg', class: "logo_image", fallback: "ロゴ画像" %>
          <% end %>
        </div>
      </nav>

      <!--メニューボタン-->
      <nav>
        <ul class="navbar-nav navbar-expand-lg">
          <% if customer_signed_in? %>
            <li class="button greeting">ようこそ　<%= current_customer.last_name %> <%= current_customer.first_name %>さん！　</li>
            <li class="button"><%= link_to " マイページ ", customers_my_page_path, class:"btn btn-default btn-lg" %></li>
            <li class="button"><%= link_to " 商品一覧 ", items_path, class:"btn btn-default btn-lg" %></li>
            <li class="button"><%= link_to " カート", cart_items_path, class:"btn btn-default btn-lg" %></li>
            <li class="button"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"btn btn-default btn-lg" %></li>
          <% else %>
            <li class="button"><%= link_to " About ", about_path, class:"btn btn-default btn-lg" %></li>
            <li class="button"><%= link_to " 商品一覧 ", items_path, class:"btn btn-default btn-lg" %></li>
            <li class="button"><%= link_to " 新規登録 ", new_customer_registration_path, class:"btn btn-default btn-lg" %></li>
            <li class="button"><%= link_to " ログイン ", new_customer_session_path, class:"btn btn-default btn-lg" %></li>
          <% end %>
        </ul>
      </nav>
      <br></br><br></br>
      <% if customer_signed_in? %>
      <div class="search-form">
      <%= form_tag(items_path,:method => 'get') do %>
        <%= text_field_tag :name %>
        <%= submit_tag '検索' %>
      <% end %>
    </div>
    <% end %>
      
  </div>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/admin_header' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
   
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="fix-wrapper">
      <%= render 'layouts/header' %>
      <main><%= yield %></main>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>